### ISSUE TITLE
Small Typo on Website

### ISSUE THREAD

**Issue by tjcouch-sil** [github/include-fragment-element#103]
Hello!

I stumbled upon a typo in your website (`include-fragment` spelled without the `c`: `inlude-fragment`) in the last paragraph.

![image](https://github.com/user-attachments/assets/6ff47e07-3bc0-4820-b241-2c3f265d04f5)

Thanks!

**Comment by keithamus** [comment]
I think this was meant for the https://github.com/keithamus/i-html repo; fixed in https://github.com/keithamus/i-html/commit/2f6934f6c117786a04ab8480b2f5baf8fb1b8b11. Thanks for the catch!
