### ISSUE TITLE
loadstart sometimes doesn't fire until the load is complete

### ISSUE THREAD

**Issue by aroben** [github/include-fragment-element#21]
include-fragment fires its events on a 0-delay timer. At least in Safari, this sometimes results in events not firing until after the load has already completed. I believe this is happening in the case where the load is served from the browser's cache; in that case the load completes so quickly that the timer for firing `loadstart` hasn't run yet.

**Comment by rianby64** [comment]
I found very interesting this repo. And I want to share my [solution/idea](https://github.com/m3co/pseudoimport-html/issues/18)... And also, I'm interesting to know if the idea to "import html" is useful or not.
